# Default values for demo-nginx-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

labels:
- key: environment
  value: demo
- key: service-type
  value: frontend
- key: app
  value: nginx

secrets:
  secret1: c2VjcmUx
  secret2: c2VjcmUy

image:
  repository: nginx
  pullPolicy: Always
  tag: 1.25.3

service:
  type: ClusterIP
  port: 80

affinity:
  enabled: false
