apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-nginx-chart.fullname" . }}
  labels:
  {{- range .Values.labels }}
    {{ .key }}: {{ .value }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
    {{- range .Values.labels }}
      {{ .key }}: {{ .value }}
    {{- end }}
  template:
    metadata:
      labels:
      {{- range .Values.labels }}
        {{ .key }}: {{ .value }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: test1
              mountPath: /test1
            - name: secrets
              mountPath: "/test2/secrets"
      volumes:
      - name: test1
        configMap:
          name: demo-configmap
          items:
            - key: configmap1.txt
              path: configmap1.txt
      - name: secrets
        secret:
          secretName: secret-data
          defaultMode: 0400
      {{- if .Values.affiniti.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-label
                operator: In
                values:
                - node-label
      {{- end }}


