apiVersion: batch/v1
kind: CronJob
metadata:
  name: helloworld
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: sa-get-resources
          containers:
            - name: task
              image: bitnami/kubectl:1.27.7
              command:
                - /bin/sh
                - -c
                - date; kubectl rollout status deployment {{ include "demo-nginx-chart.fullname" . }};