---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-get-resources
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-get-resources
  namespace: default