apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-nginx-chart.fullname" . }}
  labels:
  {{- range .Values.labels }}
    {{ .key }}: {{ .value }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- range .Values.labels }}
    {{ .key }}: {{ .value }}
  {{- end }}
